version: "3"

services:
    app:
        build: .
        ports:
            - 8080:8080
        links:
            - postgres
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: testdb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./db-data:/var/lib/postgresql/data
